services:
  db:
    image: postgres:16-alpine
    container_name: devops-db
    environment:
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: devops_pass@123
      POSTGRES_DB: devops_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./app/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  web:
    build: ./app
    container_name: devops-web
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: devops_db
      DB_USER: devops_user
      DB_PASSWORD: devops_pass@123
      FLASK_SECRET_KEY: dev-only-secret-9f3a21b
      DEFAULT_ADMIN_USER: admin
      DEFAULT_ADMIN_PASS: admin@123


volumes:
  pgdata:
